### PR TITLE
Dint 531

### PR DESCRIPTION
**Pull request by benjaminkalk**
## Description

Update snowplow addToCart handler to loop through the changed products and send for each updated product using the product context if possible and fall back to cart item context when necessary.

## Related Issue

https://jira.corp.adobe.com/browse/DINT-531

## Motivation and Context

Snowplow handler needs to be updated do to recent changes to addToCart luma store logic. see DINT-522

## How Has This Been Tested?

Partially.

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] My change requires a change to the documentation.
-   [ ] I have updated the documentation accordingly.
-   [x] I have read the **CONTRIBUTING** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

### CODE REVIEW

**Review by grahamcrackers — APPROVED** [review]
lgtm 🚀

**Review by grahamcrackers — CHANGES_REQUESTED** [review]
going to wait for feedback from @aniham

**Review by aniham — APPROVED** [review]
@benjaminkalk 🚀 thanks so much for humoring me on all my questions here!! u rock!

**Review by grahamcrackers — APPROVED** [review]
🚀

**Pull request merged**
